-- Seed initial markets for current Kenyan events
INSERT INTO markets (title, question, description, category, created_at, end_date, closing_date, resolution_date, status, resolution_source, resolution_criteria, creator_id)
VALUES
  (
    'Will Kenya''s GDP growth exceed 5% in 2024?',
    'Will Kenya''s GDP growth exceed 5% in 2024?',
    'The World Bank projects Kenya''s GDP growth at 5% for 2024. This market will resolve based on the official GDP growth rate for 2024 as reported by the Kenya National Bureau of Statistics.',
    'business',
    NOW(),
    '2024-12-31',
    '2024-12-24',
    '2024-12-31',
    'open',
    'Official GDP growth figures from the Kenya National Bureau of Statistics (KNBS)',
    'This market will resolve to YES if the official GDP growth rate for Kenya in 2024, as reported by KNBS, exceeds 5.0%. It will resolve to NO if the rate is 5.0% or lower.',
    NULL
  ),
  (
    'Will Kenya successfully issue its first green bond by October 2024?',
    'Will Kenya successfully issue its first green bond by October 2024?',
    'Kenya plans to issue its first sovereign green bond to finance climate-friendly projects. The market will resolve based on whether Kenya successfully issues a sovereign green bond.',
    'business',
    NOW(),
    '2024-10-31',
    '2024-10-24',
    '2024-10-31',
    'open',
    'Official announcements from the National Treasury and Capital Markets Authority',
    'This market will resolve to YES if the Kenyan government successfully issues its first sovereign green bond by October 31, 2024, as confirmed by official announcements from the National Treasury or Capital Markets Authority. It will resolve to NO if no such bond is issued by the deadline.',
    NULL
  ),
  (
    'Will Kenya Airways return to profitability by December 2024?',
    'Will Kenya Airways return to profitability by December 2024?',
    'Kenya Airways is implementing a turnaround strategy. This market will resolve based on whether KQ reports a net profit in its 2024 full-year financial results.',
    'business',
    NOW(),
    '2024-12-31',
    '2024-12-24',
    '2024-12-31',
    'open',
    'Kenya Airways Annual Financial Report for 2024',
    'This market will resolve to YES if Kenya Airways reports a positive net profit in its audited financial statements for the full year 2024. It will resolve to NO if the airline reports a net loss or breaks even.',
    NULL
  ),
  (
    'Will Kenya''s inflation rate fall below 6% by September 2024?',
    'Will Kenya''s inflation rate fall below 6% by September 2024?',
    'The Central Bank of Kenya targets inflation between 2.5% and 7.5%. This market resolves based on whether the official inflation rate drops below 6%.',
    'business',
    NOW(),
    '2024-09-30',
    '2024-09-23',
    '2024-09-30',
    'open',
    'Monthly inflation data from the Kenya National Bureau of Statistics',
    'This market will resolve to YES if the official month-on-month inflation rate for September 2024, as reported by KNBS, is below 6.0%. It will resolve to NO if the rate is 6.0% or higher.',
    NULL
  ),
  (
    'Will Kenya host a major international sports tournament by December 2024?',
    'Will Kenya host a major international sports tournament by December 2024?',
    'Kenya is bidding to host several international sports events. Market resolves based on whether Kenya is officially selected as host for any major international tournament.',
    'sports',
    NOW(),
    '2024-12-31',
    '2024-12-24',
    '2024-12-31',
    'open',
    'Official announcements from international sports federations or the Ministry of Sports',
    'This market will resolve to YES if Kenya is officially selected and confirmed as the host nation for any major international sports tournament (defined as a continental or global championship) by December 31, 2024. It will resolve to NO if no such selection is made.',
    NULL
  ),
  (
    'Will Kenya''s public debt exceed KES 11 trillion by November 2024?',
    'Will Kenya''s public debt exceed KES 11 trillion by November 2024?',
    'Kenya''s public debt continues to rise. This market will resolve based on whether the total public debt exceeds KES 11 trillion.',
    'business',
    NOW(),
    '2024-11-30',
    '2024-11-23',
    '2024-11-30',
    'open',
    'Official debt statistics from the National Treasury and Central Bank of Kenya',
    'This market will resolve to YES if Kenya''s total public debt (domestic and external) exceeds KES 11 trillion by November 30, 2024, as reported by the National Treasury or Central Bank. It will resolve to NO if the debt remains at or below KES 11 trillion.',
    NULL
  ),
  (
    'Will Kenya achieve universal health coverage enrollment of 80% by December 2024?',
    'Will Kenya achieve universal health coverage enrollment of 80% by December 2024?',
    'The government aims to achieve universal health coverage. Market resolves based on official enrollment statistics in the UHC program.',
    'politics',
    NOW(),
    '2024-12-31',
    '2024-12-24',
    '2024-12-31',
    'open',
    'Ministry of Health reports and NHIF enrollment statistics',
    'This market will resolve to YES if the official UHC enrollment rate reaches or exceeds 80% of the Kenyan population by December 31, 2024, as reported by the Ministry of Health or NHIF. It will resolve to NO if enrollment remains below 80%.',
    NULL
  ),
  (
    'Will Kenya''s agricultural exports exceed USD 6 billion in 2024?',
    'Will Kenya''s agricultural exports exceed USD 6 billion in 2024?',
    'Kenya aims to boost agricultural exports. This market resolves based on the total value of agricultural exports in 2024.',
    'business',
    NOW(),
    '2024-12-31',
    '2024-12-24',
    '2024-12-31',
    'open',
    'Export statistics from the Kenya National Bureau of Statistics and Central Bank of Kenya',
    'This market will resolve to YES if the total value of Kenya''s agricultural exports in 2024 exceeds USD 6 billion, as reported by KNBS or the Central Bank. It will resolve to NO if the value is USD 6 billion or less.',
    NULL
  ),
  (
    'Will Kenya complete the Nairobi Expressway extension to JKIA by December 2024?',
    'Will Kenya complete the Nairobi Expressway extension to JKIA by December 2024?',
    'The government plans to extend the Nairobi Expressway to JKIA. Market resolves based on official completion and opening of the extension.',
    'business',
    NOW(),
    '2024-12-31',
    '2024-12-24',
    '2024-12-31',
    'open',
    'Official announcements from the Kenya National Highways Authority (KeNHA)',
    'This market will resolve to YES if the Nairobi Expressway extension to JKIA is officially completed and opened for public use by December 31, 2024, as confirmed by KeNHA. It will resolve to NO if the extension is not completed or opened by the deadline.',
    NULL
  ),
  (
    'Will Harambee Stars qualify for AFCON 2025?',
    'Will Harambee Stars qualify for AFCON 2025?',
    'Kenya''s national football team is competing in AFCON 2025 qualifiers. Market resolves based on whether the team qualifies for the final tournament.',
    'sports',
    NOW(),
    '2024-12-31',
    '2024-12-24',
    '2024-12-31',
    'open',
    'Official qualification announcement from CAF (Confederation of African Football)',
    'This market will resolve to YES if the Harambee Stars secure qualification for AFCON 2025, as officially confirmed by CAF. It will resolve to NO if the team fails to qualify or is disqualified for any reason.',
    NULL
  );
